name: Build Docker Image and Push to AWS ECR
on:
  push:
    branches:
    - main

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: ap-southeast-1

         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v1

         - name: Build and push Docker image to Amazon ECR
           id: build-image
           uses: docker/build-push-action@v6
           with:
            context: .
            push: true
            tags: |
              ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
              ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest
            #platforms: linux/amd64
            #provenance: false